[workspace]
members = [
    "foundationdb",
    "foundationdb-sys",
    "foundationdb-gen",
    "foundationdb-bench",
    "foundationdb-bindingtester",
    "foundationdb-macros",
    "foundationdb-simulation",
]

[profile.release]
debug = true
