name: Scheduled correctness

on:
  workflow_dispatch:
  # https://crontab.guru/#0_*_*_*_*
  # “At minute 0.”
  schedule:
  - cron: "0 * * * *"

jobs:
  bindingtester:
    name: Binding Tester
    runs-on: ubuntu-latest
    if: github.repository == 'foundationdb-rs/foundationdb-rs'

    strategy:
      matrix:
        parallelism: ["1", "2", "3"]
        toolchain: ["1.70.0", "stable", "beta", "nightly"]
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.1.0
        with:
          version: "7.2.6"

      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        run: cargo build -p bindingtester

      - name: Setup bindingtester
        run: scripts/setup_bindingtester.sh target/debug/bindingtester

      - name: Run bindingtester
        run: scripts/run_bindingtester.sh 300
