name: PR correctness

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

jobs:
  bindingtester:
    if: contains(github.event.pull_request.labels.*.name, 'correctness')
    name: Binding Tester
    runs-on: ubuntu-latest

    strategy:
      matrix:
        parallelism: ["1", "2", "3"]
        toolchain: ["1.58.1", "stable", "beta", "nightly"]
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup FoundationDB
        uses: foundationdb-rs/foundationdb-actions-install@v2.0.0
        with:
          version: "7.1.25"

      - name: Enable tenant
        run: fdbcli --exec "configure single memory tenant_mode=optional_experimental"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p bindingtester

      - name: Setup bindingtester
        run: scripts/setup_bindingtester.sh target/debug/bindingtester

      - name: Run bindingtester
        run: scripts/run_bindingtester.sh 1000
